"""
LearnNewAgent - Meta-agent that creates new agents and swarms from a description
PLUS the actual implementation supplied by the calling model.

The calling model writes the real Python logic itself (passed as `agent_logic`)
and LearnNew just wraps it in the Single File Agent template — documentation,
metadata contract, parameter schema, error handling — then saves and hot-loads
it. The model is already smart enough to write the code; LearnNew does NOT try
to regenerate it via an external CLI.

Generated agents follow the Single File Agent pattern: one file containing
documentation, a metadata contract, and deterministic code. Output is
dual-compatible — works in the local brainstem AND is ready for the RAR
registry (https://github.com/kody-w/RAR).

Actions:
  create  — Generate and save a single agent (default)
  swarm   — Generate a multi-agent pipeline + orchestrator
  list    — List generated agents in agents/
  delete  — Remove a generated agent
  preview — Show what would be generated without writing
  submit  — Prepare a RAR-compatible submission
"""

import json
import re
import textwrap
import subprocess
from pathlib import Path
from datetime import datetime

try:
    from agents.basic_agent import BasicAgent
except ImportError:
    from basic_agent import BasicAgent


__manifest__ = {
    "schema": "rapp-agent/1.0",
    "name": "@rapp/learn_new",
    "version": "3.0.0",
    "display_name": "LearnNew",
    "description": "Creates new RAPP agents or swarms. The calling model writes the agent's logic (agent_logic) and LearnNew wraps it into a Single File Agent, then saves and hot-loads it. Output is dual-compatible with brainstem and the RAR registry.",
    "author": "RAPP",
    "tags": ["meta", "generator", "scaffolding", "learn", "swarm"],
    "category": "core",
    "quality_tier": "official",
    "requires_env": [],
    "dependencies": ["@rapp/basic_agent"],
    "example_call": {"args": {
        "action": "create",
        "agent_name": "WordCounter",
        "agent_description": "Counts the words in a piece of text.",
        "agent_parameters": "text: str",
        "agent_logic": "count = len(text.split())\nreturn json.dumps({\"status\": \"success\", \"word_count\": count})",
    }},
}


class LearnNewAgent(BasicAgent):

    AGENT_TEMPLATE = '''""\"
{description}

Auto-generated by LearnNewAgent on {date}.
Drop this file into any RAPP brainstem's agents/ directory and it works.
Compatible with the RAR registry at https://github.com/kody-w/RAR
""\"

{imports}

try:
    from agents.basic_agent import BasicAgent
except ImportError:
    from basic_agent import BasicAgent


__manifest__ = {{
    "schema": "rapp-agent/1.0",
    "name": "@{namespace}/{snake_name}",
    "version": "1.0.0",
    "display_name": "{agent_name}",
    "description": "{agent_description}",
    "author": "{author}",
    "tags": {tags_json},
    "category": "{category}",
    "quality_tier": "community",
    "requires_env": {env_json},
    "dependencies": ["@rapp/basic_agent"],
    "example_call": {{"args": {example_args_json}}},
}}


class {class_name}(BasicAgent):
    def __init__(self):
        self.name = '{agent_name}'
        self.metadata = {{
            "name": self.name,
            "description": __manifest__["description"],
            "parameters": {{
                "type": "object",
                "properties": {{
{param_properties}
                }},
                "required": {required_json}
            }}
        }}
        super().__init__(name=self.name, metadata=self.metadata)

    def perform(self{signature_params}, **kwargs) -> str:
        """
        {short_description}
{docstring_args}
        Returns:
            str: A JSON string describing the result of the operation.
        """
        try:
{logic_body}
        except Exception as e:
            return json.dumps({{
                "status": "error",
                "agent": "{agent_name}",
                "message": f"An error occurred in {agent_name}: {{str(e)}}"
            }})


if __name__ == "__main__":
    agent = {class_name}()
    print(agent.perform({example_invocation}))
'''

    SWARM_SUB_TEMPLATE = '''""\"
{description}

Part of the {swarm_name} swarm pipeline. Handles the {role} stage.
Auto-generated by LearnNewAgent on {date}.
""\"

import json
{extra_imports}
try:
    from agents.basic_agent import BasicAgent
except ImportError:
    from basic_agent import BasicAgent


__manifest__ = {{
    "schema": "rapp-agent/1.0",
    "name": "@{namespace}/{snake_name}",
    "version": "1.0.0",
    "display_name": "{agent_name}",
    "description": "{agent_description}",
    "author": "{author}",
    "tags": {tags_json},
    "category": "{category}",
    "quality_tier": "community",
    "requires_env": [],
    "dependencies": ["@rapp/basic_agent"],
    "example_call": {{"args": {{"task": "example {role} task"}}}},
}}


class {class_name}(BasicAgent):
    def __init__(self):
        self.name = '{agent_name}'
        self.metadata = {{
            "name": self.name,
            "description": __manifest__["description"],
            "parameters": {{
                "type": "object",
                "properties": {{
                    "task": {{
                        "type": "string",
                        "description": "What to {role}"
                    }}
                }},
                "required": ["task"]
            }}
        }}
        super().__init__(name=self.name, metadata=self.metadata)

    def perform(self, **kwargs):
        task = kwargs.get('task', '')

{perform_body}


if __name__ == "__main__":
    a = {class_name}()
    print(a.perform(task="test"))
'''

    SWARM_ORCH_TEMPLATE = '''""\"
{description}

Orchestrates the {swarm_name} swarm by coordinating sub-agents:
{sub_agent_list}

Auto-generated by LearnNewAgent on {date}.
Drop this file into any RAPP brainstem's agents/ directory and it works.
Use SwarmFactory to converge the sub-agents into a single shareable singleton.
""\"

import json
import os

try:
    from agents.basic_agent import BasicAgent
except ImportError:
    from basic_agent import BasicAgent

{sub_agent_imports}


__manifest__ = {{
    "schema": "rapp-agent/1.0",
    "name": "@{namespace}/{snake_name}",
    "version": "1.0.0",
    "display_name": "{swarm_name}",
    "description": "{agent_description}",
    "author": "{author}",
    "tags": {tags_json},
    "category": "{category}",
    "quality_tier": "community",
    "requires_env": [],
    "dependencies": ["@rapp/basic_agent"],
    "example_call": {{"args": {{"task": "Run the {swarm_name} pipeline"}}}},
}}


class {class_name}(BasicAgent):
    def __init__(self):
        self.name = '{swarm_name}'
        self.metadata = {{
            "name": self.name,
            "description": __manifest__["description"],
            "parameters": {{
                "type": "object",
                "properties": {{
                    "task": {{
                        "type": "string",
                        "description": "What you want the swarm to do"
                    }},
                    "sub_agent": {{
                        "type": "string",
                        "description": "Optional: run a specific sub-agent by name instead of the full pipeline"
                    }}
                }},
                "required": ["task"]
            }}
        }}
        super().__init__(name=self.name, metadata=self.metadata)
        self._agents = {{}}

    def _get_agent(self, name):
        if name not in self._agents:
            agents = {{{agent_map}}}
            cls = agents.get(name)
            if cls:
                self._agents[name] = cls()
        return self._agents.get(name)

    def perform(self, **kwargs):
        task = kwargs.get('task', '')
        sub_agent = kwargs.get('sub_agent', '')

        if sub_agent:
            agent = self._get_agent(sub_agent)
            if not agent:
                available = {agent_names_json}
                return json.dumps({{"status": "error",
                    "message": f"Unknown sub-agent '{{sub_agent}}'. Available: {{available}}"}})
            return agent.perform(task=task, **kwargs)

        results = {{}}
        pipeline = {pipeline_json}
        slush = {{}}
        for step_name in pipeline:
            agent = self._get_agent(step_name)
            if agent:
                agent_kwargs = {{"task": task}}
                if hasattr(agent, 'context'):
                    agent.context = type('Ctx', (), {{'slush': slush}})()
                r = agent.perform(**agent_kwargs)
                results[step_name] = r
                try:
                    parsed = json.loads(r)
                    if 'data_slush' in parsed:
                        slush.update(parsed['data_slush'])
                except (json.JSONDecodeError, TypeError):
                    pass

        return json.dumps({{
            "status": "ok",
            "swarm": "{swarm_name}",
            "pipeline_steps": len(pipeline),
            "results": results,
        }})


if __name__ == "__main__":
    a = {class_name}()
    print(a.perform(task="test"))
'''

    def __init__(self):
        self.name = 'LearnNew'
        self.metadata = {
            "name": self.name,
            "description": (
                "Creates a new RAPP agent (or swarm) and hot-loads it. YOU write the "
                "agent's implementation: pass the real Python code as 'agent_logic' "
                "(reference the parameters by name, end with a `return` of a string — "
                "usually json.dumps(...)). LearnNew wraps your code in the Single File "
                "Agent template with metadata, docstring, and error handling, saves it "
                "to agents/, and loads it immediately. "
                "Actions: 'create' generates a single agent, 'swarm' creates a "
                "multi-agent pipeline, 'list' shows generated agents, 'delete' removes "
                "one, 'preview' dry-runs generation, 'submit' prepares a RAR submission. "
                "Call this when the user wants to teach the brainstem a new capability "
                "or build a custom agent."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "action": {
                        "type": "string",
                        "description": "Action to perform. Defaults to 'create'.",
                        "enum": ["create", "swarm", "list", "delete", "preview", "submit"]
                    },
                    "agent_name": {
                        "type": "string",
                        "description": "Name for the new agent in CamelCase (e.g. 'WebSummarizer'). Optional — derived from the description if omitted."
                    },
                    "agent_description": {
                        "type": "string",
                        "description": "A clear, one-or-two sentence description of what the agent does. Becomes the tool description the LLM sees when deciding to call it."
                    },
                    "agent_parameters": {
                        "type": "string",
                        "description": "Comma-separated list of the agent's parameters as 'name: type' pairs, e.g. 'url: str, limit: int = 5'. Types: str, int, float, bool, list, dict. Defaults (= value) make a parameter optional. Omit for a single 'query: str' parameter."
                    },
                    "agent_logic": {
                        "type": "string",
                        "description": "The actual Python code for the body of perform(). Reference the declared parameters by name as local variables. Use json (already imported) and any stdlib module you need. MUST end by returning a string (e.g. `return json.dumps({\"status\": \"success\", ...})`). Do NOT include the def line, the try/except, or imports of basic_agent — only the logic. This is the implementation; write it fully, do not leave a stub."
                    },
                    "category": {
                        "type": "string",
                        "enum": ["general", "productivity", "sales", "support", "data",
                                 "automation", "integrations", "devtools", "pipeline"],
                        "description": "Agent category for the registry."
                    },
                    "namespace": {
                        "type": "string",
                        "description": "RAR namespace for submission (e.g. @myname). Defaults to @rapp."
                    },
                    "agents_in_swarm": {
                        "type": "string",
                        "description": "For action='swarm': comma-separated sub-agent roles (e.g. 'researcher,writer,editor')."
                    },
                    "requires_env": {
                        "type": "string",
                        "description": "Comma-separated env vars the agent needs (e.g. 'API_KEY,WEBHOOK_URL')."
                    }
                },
                "required": []
            }
        }
        super().__init__(name=self.name, metadata=self.metadata)
        self.agents_dir = Path(__file__).parent

    def perform(self, **kwargs):
        action = kwargs.pop('action', 'create')

        # New contract: caller supplies the implementation; aliases kept for back-compat.
        description = (kwargs.pop('agent_description', '')
                       or kwargs.pop('description', '')
                       or kwargs.pop('query', ''))
        name = kwargs.pop('agent_name', '') or kwargs.pop('name', '')
        agent_parameters = kwargs.pop('agent_parameters', '')
        agent_logic = kwargs.pop('agent_logic', '')

        if action == 'list':
            return self._list_generated_agents()
        elif action == 'delete':
            return self._delete_agent(name or description)
        elif action == 'preview':
            if kwargs.get('agents_in_swarm'):
                return self._create_swarm(description, name, write=False, **kwargs)
            return self._create_agent(description, name, agent_parameters,
                                      agent_logic, write=False, **kwargs)
        elif action == 'submit':
            return self._prepare_submit(description, name, agent_parameters,
                                        agent_logic, **kwargs)
        elif action == 'swarm':
            return self._create_swarm(description, name, write=True, **kwargs)
        else:
            return self._create_agent(description, name, agent_parameters,
                                      agent_logic, write=True, **kwargs)

    # ── Single agent creation ─────────────────────────────────────────────

    def _create_agent(self, description, name='', agent_parameters='',
                      agent_logic='', write=True, **kwargs):
        if not description and not name:
            return json.dumps({
                "status": "error",
                "message": "Please provide agent_description (and ideally agent_logic — "
                           "the Python code for what the agent should do)."
            })

        if not name:
            name = self._generate_name(description)

        name = self._sanitize_name(name)
        if not re.match(r'^[A-Z][a-zA-Z0-9]*$', name):
            return json.dumps({
                "status": "error",
                "message": f"Invalid agent name '{name}'. Use CamelCase (e.g. 'WebSummarizer')."
            })

        class_name = f"{name}Agent"
        snake = self._to_snake_case(name)
        file_name = f"{snake}_agent.py"
        file_path = self.agents_dir / file_name

        if write and file_path.exists():
            return json.dumps({
                "status": "error",
                "message": f"Agent '{name}' already exists at {file_path}. "
                           f"Delete it first or choose a different name."
            })

        agent_code = self._generate_agent_code(
            description or name, name, class_name,
            agent_parameters, agent_logic, **kwargs)

        # Syntax-check before writing so a bad agent_logic never lands a broken file.
        syntax_err = self._syntax_check(agent_code)
        if syntax_err:
            return json.dumps({
                "status": "error",
                "message": f"Generated agent has a syntax error: {syntax_err}. "
                           f"Check the agent_logic you supplied (it becomes the body of perform()).",
                "code": agent_code,
            })

        if not write:
            return json.dumps({
                "status": "ok",
                "action": "preview",
                "filename": file_name,
                "class_name": class_name,
                "display_name": name,
                "lines": len(agent_code.split('\n')),
                "code": agent_code,
                "message": f"Preview of {file_name} — use action='create' to write it."
            })

        try:
            file_path.write_text(agent_code)
        except Exception as e:
            return json.dumps({"status": "error", "message": f"Failed to write agent file: {e}"})

        hot_load_result = self._hot_load_agent(file_path, class_name)

        result = {
            "status": "success",
            "action": "create",
            "message": f"Created and loaded agent '{name}'",
            "agent_name": name,
            "filename": file_name,
            "file_path": str(file_path),
            "lines": len(agent_code.split('\n')),
            "hot_loaded": hot_load_result.get("success", False),
            "description": (description or name)[:200],
            "hint": (
                f"Agent saved to agents/{file_name} — it auto-loads on the next request. "
                f"Edit the perform() method to customize the logic. "
                f"To submit to RAR, re-run with action='submit'."
            ),
        }

        if hot_load_result.get("installed_deps"):
            result["installed_dependencies"] = hot_load_result["installed_deps"]
        if not hot_load_result.get("success"):
            result["hot_load_error"] = hot_load_result.get("error")
            if hot_load_result.get("hint"):
                result["hot_load_hint"] = hot_load_result["hint"]

        return json.dumps(result)

    # ── Swarm creation ────────────────────────────────────────────────────

    def _create_swarm(self, description, swarm_name='', write=True, **kwargs):
        if not description:
            return json.dumps({
                "status": "error",
                "message": "Please provide a description of what the swarm should do."
            })

        if not swarm_name:
            swarm_name = self._generate_name(description)
        swarm_name = self._sanitize_name(swarm_name)

        agents_in_swarm = kwargs.get('agents_in_swarm', '')
        if agents_in_swarm:
            sub_roles = [s.strip() for s in agents_in_swarm.split(",") if s.strip()]
        else:
            sub_roles = ["researcher", "processor", "formatter"]

        category = kwargs.get('category', 'pipeline')
        namespace = (kwargs.get('namespace', '') or 'rapp').lstrip('@')
        env_list = [e.strip() for e in (kwargs.get('requires_env', '') or '').split(",") if e.strip()]
        tags = self._generate_tags(description) + ["swarm"]

        generated_files = []

        for role in sub_roles:
            sub_name = self._sanitize_name(role)
            sub_snake = self._to_snake_case(swarm_name) + "_" + self._to_snake_case(sub_name)
            sub_class = f"{sub_name}Agent"
            sub_filename = f"{sub_snake}_agent.py"
            sub_desc = f"{sub_name} sub-agent for the {swarm_name} swarm."

            perform_body = self._default_swarm_body(role)

            sub_code = self.SWARM_SUB_TEMPLATE.format(
                description=sub_desc,
                swarm_name=swarm_name,
                role=role.lower(),
                date=datetime.now().strftime("%Y-%m-%d %H:%M"),
                namespace=namespace,
                snake_name=sub_snake,
                agent_name=sub_name,
                agent_description=sub_desc.replace('"', '\\"'),
                author=namespace,
                class_name=sub_class,
                category=category,
                tags_json=json.dumps([category, "swarm-member", self._to_snake_case(role)]),
                env_json=json.dumps(env_list),
                perform_body=perform_body,
                extra_imports="",
            )

            if write:
                dest = self.agents_dir / sub_filename
                try:
                    dest.write_text(sub_code)
                except Exception as e:
                    return json.dumps({"status": "error",
                                       "message": f"Failed to write {sub_filename}: {e}"})

            generated_files.append({
                "filename": sub_filename,
                "class": sub_class,
                "role": role,
                "snake": sub_snake,
            })

        orch_snake = self._to_snake_case(swarm_name)
        orch_filename = f"{orch_snake}_agent.py"
        orch_class = f"{swarm_name}Agent"
        safe_desc = description.replace('"', '\\"').replace('\n', ' ')[:200]

        sub_imports = "\n".join(
            f"from agents.{f['snake']}_agent import {f['class']}"
            for f in generated_files
        )
        agent_map = ", ".join(
            f'"{self._to_snake_case(f["role"])}": {f["class"]}'
            for f in generated_files
        )
        agent_names = [self._to_snake_case(f["role"]) for f in generated_files]
        sub_list_str = "\n".join(f"  - {f['class']} ({f['role']})" for f in generated_files)

        orch_code = self.SWARM_ORCH_TEMPLATE.format(
            description=description,
            swarm_name=swarm_name,
            sub_agent_list=sub_list_str,
            date=datetime.now().strftime("%Y-%m-%d %H:%M"),
            namespace=namespace,
            snake_name=orch_snake,
            agent_description=safe_desc,
            author=namespace,
            class_name=orch_class,
            category=category,
            tags_json=json.dumps(tags),
            sub_agent_imports=sub_imports,
            agent_map=agent_map,
            agent_names_json=json.dumps(agent_names),
            pipeline_json=json.dumps(agent_names),
        )

        if write:
            dest = self.agents_dir / orch_filename
            try:
                dest.write_text(orch_code)
            except Exception as e:
                return json.dumps({"status": "error",
                                   "message": f"Failed to write {orch_filename}: {e}"})

        generated_files.append({
            "filename": orch_filename,
            "class": orch_class,
            "role": "orchestrator",
            "is_orchestrator": True,
        })

        all_filenames = [f["filename"] for f in generated_files]

        result = {
            "status": "success",
            "action": "swarm" if write else "preview",
            "swarm_name": swarm_name,
            "files_generated": len(generated_files),
            "filenames": all_filenames,
            "sub_agents": sub_roles,
            "orchestrator": orch_filename,
            "message": (
                f"Created {swarm_name} swarm: {len(sub_roles)} sub-agents + 1 orchestrator "
                f"({len(generated_files)} files total). "
            ),
        }

        if write:
            result["message"] += (
                "All written to agents/ — they auto-load on next request. Each "
                "sub-agent has a stub perform() — re-run LearnNew with action='create' "
                "(supplying agent_logic) to flesh out a stage, or edit the files directly. "
                "Use SwarmFactory (action=build) to converge them into a single "
                "shareable singleton file."
            )

            for f in generated_files:
                if not f.get("is_orchestrator"):
                    fpath = self.agents_dir / f["filename"]
                    self._hot_load_agent(fpath, f["class"])
            orch_path = self.agents_dir / orch_filename
            self._hot_load_agent(orch_path, orch_class)
        else:
            result["orchestrator_code"] = orch_code

        return json.dumps(result)

    def _default_swarm_body(self, role):
        role_safe = role.lower().replace('"', '').replace('\\', '')
        return (
            f'        # TODO: implement the {role_safe} stage. Receives `task`, returns a JSON string.\n'
            f'        return json.dumps({{\n'
            f'            "status": "ok",\n'
            f'            "role": "{role_safe}",\n'
            f'            "task": task,\n'
            f'            "result": f"{role_safe} stage processed: {{task}}",\n'
            f'            "data_slush": {{}}\n'
            f'        }})'
        )

    # ── RAR submission ────────────────────────────────────────────────────

    def _prepare_submit(self, description, name='', agent_parameters='',
                        agent_logic='', **kwargs):
        preview = json.loads(self._create_agent(
            description, name, agent_parameters, agent_logic, write=False, **kwargs))
        if preview.get("status") != "ok":
            return json.dumps(preview)

        code = preview.get("code", "")
        namespace = (kwargs.get('namespace', '') or 'rapp').lstrip('@')
        filename = preview["filename"]
        rar_path = f"agents/@{namespace}/{filename}"

        issue_title = f"[AGENT] @{namespace}/{filename.replace('.py', '')}"

        return json.dumps({
            "status": "ok",
            "action": "submit",
            "filename": filename,
            "namespace": f"@{namespace}",
            "rar_path": rar_path,
            "issue_title": issue_title,
            "code": code,
            "message": (
                f"Agent ready for RAR submission.\n\n"
                f"Option 1 — GitHub Issue:\n"
                f"  Open https://github.com/kody-w/RAR/issues/new\n"
                f"  Title: {issue_title}\n"
                f"  Body: paste the agent code as a Python code block.\n\n"
                f"Option 2 — Pull Request:\n"
                f"  Add the file to {rar_path} and open a PR.\n\n"
                f"The registry CI validates the manifest and runs security checks."
            ),
        })

    # ── Name generation ───────────────────────────────────────────────────

    def _generate_name(self, description):
        words = description.lower().split()
        keywords = [w for w in words if len(w) > 3 and w not in
                    {'that', 'this', 'with', 'from', 'agent', 'create', 'make',
                     'want', 'should', 'would', 'could', 'learn', 'teach',
                     'build', 'about', 'which', 'their', 'your', 'they'}]

        if keywords:
            return ''.join(w.capitalize() for w in keywords[:2])
        return 'Custom'

    def _sanitize_name(self, name):
        name = re.sub(r'[^a-zA-Z0-9]', '', name)
        if name and not name[0].isalpha():
            name = 'Agent' + name
        if name:
            name = name[0].upper() + name[1:]
        return name or 'Custom'

    def _to_snake_case(self, name):
        s1 = re.sub('(.)([A-Z][a-z]+)', r'\1_\2', name)
        return re.sub('([a-z0-9])([A-Z])', r'\1_\2', s1).lower()

    # ── Parameter parsing ─────────────────────────────────────────────────

    _JSON_TYPES = {
        'str': 'string', 'int': 'integer', 'float': 'number',
        'bool': 'boolean', 'list': 'array', 'dict': 'object',
    }

    def _json_type(self, py_type):
        base = py_type.strip().lower().split('[')[0]
        return self._JSON_TYPES.get(base, 'string')

    def _parse_params(self, agent_parameters):
        """Parse 'name: type = default, other: int' into structured param dicts."""
        if not agent_parameters or not agent_parameters.strip():
            agent_parameters = "query: str"

        params = []
        for raw in agent_parameters.split(','):
            raw = raw.strip()
            if not raw:
                continue
            if ':' in raw:
                name, rest = raw.split(':', 1)
            else:
                name, rest = raw, 'str'
            name = re.sub(r'[^a-zA-Z0-9_]', '', name.strip())
            if not name:
                continue
            if name[0].isdigit():
                name = 'arg_' + name
            rest = rest.strip()
            default = None
            has_default = False
            if '=' in rest:
                type_part, default = rest.split('=', 1)
                default = default.strip()
                has_default = True
            else:
                type_part = rest
            py_type = (type_part.strip() or 'str')
            params.append({
                'name': name,
                'py_type': py_type,
                'json_type': self._json_type(py_type),
                'default': default,
                'has_default': has_default,
            })
        return params

    def _build_signature(self, params):
        parts = []
        for p in params:
            default = p['default'] if p['has_default'] else 'None'
            parts.append(f"{p['name']}: {p['py_type']} = {default}")
        return (", " + ", ".join(parts)) if parts else ""

    def _build_properties_block(self, params):
        lines = []
        n = len(params)
        for i, p in enumerate(params):
            comma = "," if i < n - 1 else ""
            desc = (f"Value for `{p['name']}`. The assistant provides an appropriate "
                    f"value based on the user's request.")
            lines.append(f'                    "{p["name"]}": {{')
            lines.append(f'                        "type": "{p["json_type"]}",')
            lines.append(f'                        "description": "{desc}"')
            lines.append(f'                    }}{comma}')
        return "\n".join(lines)

    def _build_required(self, params):
        return [p['name'] for p in params if not p['has_default']]

    def _build_docstring_args(self, params):
        if not params:
            return ""
        lines = ["        Args:"]
        for p in params:
            lines.append(
                f"            {p['name']} ({p['py_type']}): Provided by the assistant "
                f"based on the user's request.")
        return "\n".join(lines)

    def _build_example_invocation(self, params):
        if not params:
            return ""
        p = params[0]
        if p['json_type'] in ('integer', 'number'):
            val = "1"
        elif p['json_type'] == 'boolean':
            val = "True"
        elif p['json_type'] == 'array':
            val = "[]"
        elif p['json_type'] == 'object':
            val = "{}"
        else:
            val = '"test"'
        return f"{p['name']}={val}"

    def _build_example_args(self, params):
        example = {}
        for p in params[:2]:
            if p['json_type'] in ('integer', 'number'):
                example[p['name']] = 1
            elif p['json_type'] == 'boolean':
                example[p['name']] = True
            elif p['json_type'] == 'array':
                example[p['name']] = []
            elif p['json_type'] == 'object':
                example[p['name']] = {}
            else:
                example[p['name']] = f"example {p['name']}"
        return example

    # ── Code generation ───────────────────────────────────────────────────

    def _generate_agent_code(self, description, name, class_name,
                             agent_parameters='', agent_logic='', **kwargs):
        params = self._parse_params(agent_parameters)

        if not agent_logic or not agent_logic.strip():
            agent_logic = self._default_logic()
        logic_body = self._indent_code(agent_logic, 12)

        imports = "\n".join(self._infer_imports(agent_logic, description))

        safe_desc = description.replace('"', '\\"').replace('\n', ' ')[:200]
        short_desc = description.split('\n')[0].replace('"', "'").strip()[:200] or name
        tags = self._generate_tags(description)
        snake = self._to_snake_case(name)

        category = kwargs.get('category', 'general')
        namespace = (kwargs.get('namespace', '') or 'rapp').lstrip('@')
        env_list = [e.strip() for e in (kwargs.get('requires_env', '') or '').split(",") if e.strip()]

        return self.AGENT_TEMPLATE.format(
            description=description,
            date=datetime.now().strftime("%Y-%m-%d %H:%M"),
            class_name=class_name,
            agent_name=name,
            agent_description=safe_desc,
            short_description=short_desc,
            imports=imports,
            signature_params=self._build_signature(params),
            param_properties=self._build_properties_block(params),
            required_json=json.dumps(self._build_required(params)),
            docstring_args=self._build_docstring_args(params),
            logic_body=logic_body,
            example_invocation=self._build_example_invocation(params),
            tags_json=json.dumps(tags),
            category=category,
            namespace=namespace,
            snake_name=snake,
            author=namespace,
            env_json=json.dumps(env_list),
            # repr() so booleans/None render as valid Python (True/None), since the
            # manifest is a Python literal, not JSON.
            example_args_json=repr(self._build_example_args(params)),
        )

    def _default_logic(self):
        return (
            "# No agent_logic was supplied — this is a stub. Edit perform() to implement.\n"
            "return json.dumps({\n"
            '    "status": "ok",\n'
            '    "agent": self.name,\n'
            '    "inputs": kwargs,\n'
            '    "note": "This agent has no logic yet. Re-run LearnNew with agent_logic, or edit perform()."\n'
            "})"
        )

    def _indent_code(self, code, spaces):
        """Dedent the supplied code to a common baseline, then re-indent uniformly.

        This makes the wrapper robust whether the caller hands over already-indented
        code or a flush-left block.
        """
        code = textwrap.dedent(code).strip('\n')
        if not code.strip():
            code = self._default_logic()
        pad = ' ' * spaces
        return '\n'.join(pad + line if line.strip() else '' for line in code.split('\n'))

    def _infer_imports(self, logic, description):
        """Module-level imports needed by the generated agent.

        `json` is always present (the error handler uses it). Everything else is
        added only when the supplied logic or description actually references it,
        so generated files stay clean. Non-stdlib modules (requests, bs4) are still
        auto-installed by the hot-loader if they end up missing.
        """
        text = (logic or '') + '\n' + (description or '')
        imports = ['import json']
        mapping = [
            (r'\bre\.', 'import re'),
            (r'\bos\.', 'import os'),
            (r'\bsys\.', 'import sys'),
            (r'\bmath\.', 'import math'),
            (r'\brandom\.', 'import random'),
            (r'\btime\.', 'import time'),
            (r'\bdatetime\b', 'from datetime import datetime'),
            (r'\bPath\b', 'from pathlib import Path'),
            (r'\burllib\.', 'import urllib.request'),
            (r'\bcsv\.', 'import csv'),
            (r'\bbase64\.', 'import base64'),
            (r'\bhashlib\.', 'import hashlib'),
            (r'\bsubprocess\.', 'import subprocess'),
            (r'\brequests\.', 'import requests'),
            (r'\bBeautifulSoup\b', 'from bs4 import BeautifulSoup'),
        ]
        for pattern, stmt in mapping:
            if re.search(pattern, text) and stmt not in imports:
                imports.append(stmt)
        return imports

    def _generate_tags(self, description):
        tags = []
        desc_lower = description.lower()
        tag_map = {
            'weather': 'weather', 'api': 'api', 'web': 'web',
            'file': 'filesystem', 'data': 'data', 'search': 'search',
            'email': 'email', 'database': 'database', 'sql': 'database',
            'news': 'news', 'schedule': 'scheduling', 'voice': 'voice',
            'stock': 'finance', 'price': 'finance', 'video': 'media',
            'image': 'media', 'summarize': 'nlp', 'translate': 'nlp',
            'monitor': 'monitoring', 'track': 'tracking', 'slack': 'messaging',
        }
        for keyword, tag in tag_map.items():
            if keyword in desc_lower and tag not in tags:
                tags.append(tag)
        return tags or ['custom']

    def _syntax_check(self, code):
        """Return None if the generated code parses, else a short error string."""
        import ast
        try:
            ast.parse(code)
            return None
        except SyntaxError as e:
            return f"line {e.lineno}: {e.msg}"

    # ── Hot-loading ───────────────────────────────────────────────────────

    def _hot_load_agent(self, file_path, class_name):
        try:
            import importlib.util

            code = file_path.read_text()
            missing_deps = self._detect_missing_imports(code)

            if missing_deps:
                install_result = self._install_dependencies(missing_deps)
                if not install_result['success']:
                    return {
                        "success": False,
                        "error": f"Failed to install dependencies: {install_result['error']}",
                        "missing_deps": missing_deps
                    }

            spec = importlib.util.spec_from_file_location(file_path.stem, file_path)
            module = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(module)

            agent_class = getattr(module, class_name, None)
            if agent_class is None:
                return {"success": False, "error": "Class not found in module"}

            import sys
            module_name = f"agents.{file_path.stem}"
            sys.modules[module_name] = module

            result = {"success": True, "class": class_name}
            if missing_deps:
                result["installed_deps"] = missing_deps
            return result

        except ModuleNotFoundError as e:
            missing = str(e).split("'")[1] if "'" in str(e) else str(e)
            return {
                "success": False,
                "error": f"Missing module: {missing}",
                "hint": f"Try: pip install {missing}"
            }
        except Exception as e:
            return {"success": False, "error": str(e)}

    def _detect_missing_imports(self, code):
        import importlib

        missing = []
        import_pattern = r'^(?:from\s+(\w+)|import\s+(\w+))'
        for line in code.split('\n'):
            line = line.strip()
            match = re.match(import_pattern, line)
            if match:
                module_name = match.group(1) or match.group(2)
                if module_name in self._stdlib_modules():
                    continue
                if module_name in ('agents', 'basic_agent'):
                    continue
                try:
                    importlib.import_module(module_name)
                except ImportError:
                    pkg_name = self._module_to_package(module_name)
                    if pkg_name not in missing:
                        missing.append(pkg_name)
        return missing

    def _module_to_package(self, module_name):
        mappings = {
            'cv2': 'opencv-python',
            'PIL': 'Pillow',
            'sklearn': 'scikit-learn',
            'yaml': 'pyyaml',
            'bs4': 'beautifulsoup4',
            'dotenv': 'python-dotenv',
            'jwt': 'pyjwt',
            'serial': 'pyserial',
            'usb': 'pyusb',
            'Crypto': 'pycryptodome',
        }
        return mappings.get(module_name, module_name)

    def _stdlib_modules(self):
        return {
            'abc', 'argparse', 'ast', 'asyncio', 'base64', 'collections',
            'contextlib', 'copy', 'csv', 'datetime', 'decimal', 'difflib',
            'email', 'enum', 'functools', 'glob', 'gzip', 'hashlib', 'heapq',
            'html', 'http', 'importlib', 'inspect', 'io', 'itertools', 'json',
            'logging', 'math', 'mimetypes', 'multiprocessing', 'operator', 'os',
            'pathlib', 'pickle', 'platform', 'pprint', 'queue', 'random', 're',
            'shutil', 'signal', 'socket', 'sqlite3', 'ssl', 'statistics',
            'string', 'struct', 'subprocess', 'sys', 'tempfile', 'textwrap',
            'threading', 'time', 'traceback', 'types', 'typing', 'unittest',
            'urllib', 'uuid', 'warnings', 'weakref', 'xml', 'zipfile', 'zlib'
        }

    def _install_dependencies(self, packages):
        if not packages:
            return {"success": True}
        try:
            import sys
            for pkg in packages:
                result = subprocess.run(
                    [sys.executable, '-m', 'pip', 'install', '--quiet', pkg],
                    capture_output=True, text=True, timeout=60
                )
                if result.returncode != 0:
                    return {"success": False,
                            "error": f"pip install {pkg} failed: {result.stderr}"}
            return {"success": True, "installed": packages}
        except subprocess.TimeoutExpired:
            return {"success": False, "error": "pip install timed out"}
        except Exception as e:
            return {"success": False, "error": str(e)}

    # ── List / Delete ─────────────────────────────────────────────────────

    def _list_generated_agents(self):
        agents = []
        core = {'basic_agent.py', 'save_memory_agent.py', 'recall_memory_agent.py',
                'learn_new_agent.py', 'swarm_factory_agent.py'}
        for f in sorted(self.agents_dir.glob('*_agent.py')):
            if f.name in core:
                continue
            content = f.read_text()
            is_generated = 'Auto-generated by LearnNewAgent' in content
            agents.append({
                "name": f.stem.replace('_agent', ''),
                "file": f.name,
                "auto_generated": is_generated
            })
        return json.dumps({
            "status": "success",
            "agents": agents,
            "count": len(agents)
        })

    def _delete_agent(self, name):
        if not name:
            return json.dumps({
                "status": "error",
                "message": "Please provide the agent name to delete."
            })

        snake_name = self._to_snake_case(self._sanitize_name(name))
        file_path = self.agents_dir / f"{snake_name}_agent.py"

        if not file_path.exists():
            for f in self.agents_dir.glob('*_agent.py'):
                if name.lower() in f.name.lower():
                    file_path = f
                    break

        if not file_path.exists():
            return json.dumps({
                "status": "error",
                "message": f"Agent '{name}' not found."
            })

        core = {'basic_agent.py', 'save_memory_agent.py', 'recall_memory_agent.py',
                'learn_new_agent.py', 'swarm_factory_agent.py'}
        if file_path.name in core:
            return json.dumps({
                "status": "error",
                "message": "Cannot delete core agents."
            })

        try:
            file_path.unlink()
            return json.dumps({
                "status": "success",
                "message": f"Deleted agent '{name}'",
                "file": str(file_path)
            })
        except Exception as e:
            return json.dumps({"status": "error", "message": str(e)})


if __name__ == "__main__":
    a = LearnNewAgent()
    print(a.perform(
        action="preview",
        agent_name="HabitTracker",
        agent_description="Tracks daily habits and computes streaks.",
        agent_parameters="habit: str, days: int = 7",
        agent_logic=(
            "streak = min(days, 30)\n"
            "return json.dumps({\n"
            '    "status": "success",\n'
            '    "habit": habit,\n'
            '    "streak_days": streak\n'
            "})"
        ),
    ))
